AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  launch-best-aircon

  Sample SAM Template for launch-best-aircon
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  LaunchBestAirconFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: launch-best-aircon/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        LaunchBestAircon:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /launch
            Method: get
      Environment:
        Variables:
          MACKEREL_API_KEY: !Ref MackerelApiKey
          IFTTT_API_KEY: !Ref IftttApiKey

Parameters:
  MackerelApiKey:
    Type: String
  IftttApiKey:
    Type: String

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LaunchBestAirconApi:
    Description: "API Gateway endpoint URL for Prod stage for Launch Best Aircon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/launch/"
  LaunchBestAirconFunction:
    Description: "Launch Best Aircon Lambda Function ARN"
    Value: !GetAtt LaunchBestAirconFunction.Arn
  LaunchBestAirconFunctionIamRole:
    Description: "Implicit IAM Role created for Launch Best Aircon function"
    Value: !GetAtt LaunchBestAirconFunctionRole.Arn
